### ISSUE TITLE
Unhandled error after meteor update to 1.1.0.2

### ISSUE THREAD

**Issue by mattjmorris** [rjsmith/meteor-robotframework#9]
I'm trying to run the official example robotframework tests that are published in the meteor-velocity/velocity-examples repository. After updating Meteor to 1.1.0.2, I receive the following error when running via the 'meteor' command

=> App running at: http://localhost:3000/
? [velocity] robotframework is starting a mirror at http://localhost:52300/.
? [velocity] You can see the mirror logs at: tail -f .../velocity-examples/leaderboard-robotframework/.meteor/local/log/robotframework.log
? [rsbatech:robotframework] Robot Framework is running
? (STDERR) 
? (STDERR) events.js:72
? (STDERR)         throw er; // Unhandled 'error' event
? (STDERR)               ^
? (STDERR) Error: spawn ENOTDIR
? (STDERR)     at errnoException (child_process.js:1011:11)
? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by rjsmith** [comment]
OK, thanks for the report. I'll take a look....

**Comment by rjsmith** [comment]
quick question: what OS are you trying to run this on?   If Windows, then meteor-robotframework does not support it yet (see #6 ).

**Comment by mattjmorris** [comment]
Thanks for looking into this so quickly. I'm on OSX Yosemite. 

Please let me know if I can give you any other info or try anything that may be diagnostic.

**Comment by rjsmith** [comment]
OK, think I have reproduced this on OSX Yosemite. Now to fix it .. may take some time....

**Comment by mattjmorris** [comment]
Let me know if there is anything I can do to help.

**Comment by rjsmith** [comment]
I have published a new version of the meteor-robotframework package, v0.4.0, and [sent a PR](https://github.com/meteor-velocity/velocity-examples/pull/45) to the velocity-examples project.  Both of which together should hopefully resolve this issue, or at least, prevent the system getting to the state where it might occur..

**Comment by mattjmorris** [comment]
I just tested the 0.4.0 release with a brand new default meteor app and am getting the same error. 

Here are details of what my meteor project has: 

$ meteor --version
Meteor 1.1.0.2

$ meteor list
autopublish              1.0.3  Publish the entire database to all clients
insecure                 1.0.3  Allow all database writes by default
meteor-platform          1.2.2  Include a standard set of Meteor packages in your app
rsbatech:robotframework  0.4.0  Robot Framework for Meteor Velocity

Any ideas of what I may try to do to fix?

**Comment by rjsmith** [comment]
Hmm. I can't reproduce this on my own OSX Yosemite machine, using the included RF sample tests (NB: you have to restart meteor after adding the sample tests to the project for Velocity to detect them).

Could you run meteor with `VELOCITY_DEBUG=1 RF_DEBUG=1 meteor` and post the log output ?  Also, a copy of the RF test file you are using, if not the samle tests? What ${BROWSER} are you trying to use ? PhantomJS ? Chrome ?   

btw - my PR was merged into the velocity-examples project.

**Comment by mattjmorris** [comment]
Richard, thanks for continuing to help with this. In addition to using Velocity+robotframework for my own app, I'm hoping to demo the framework at the next meetup of my local meteor group.

I was able to get robotframework working via the Python runner (pybot) but still receive the error when attempting to use it via Velocity. 

I deleted my old version of the velocity-examples project, re-cloned, and ran via your suggested debug flags. Here is the output I received (I removed the timestamps for readability and parts of my full path):

$ VELOCITY_DEBUG=1 RF_DEBUG=1 meteor
[[[[[ /velocity-examples/leaderboard-robotframework ]]]]]

=> Started proxy.
=> Started MongoDB.
? [velocity] adding velocity core
? [velocity] Not adding mirror-registrar because NODE_ENV is development and IS_MIRROR is false
? [velocity] Register framework robotframework with regex robotframework/.+.(txt|robot|xhtml|htm|html|tsv)$
? [velocity] Server startup
? [velocity] app dir /velocity-examples/leaderboard-robotframework
? [velocity] config = {
?   "robotframework": {
?     "regex": "robotframework/.+\.(txt|robot|xhtml|htm|html|tsv)$",
?     "name": "robotframework",
?     "_regexp": {}
?   }
? }
? [velocity] resetting the world
? [velocity] frameworks with disable auto reset: []
? [velocity] Add paths to watcher [ /velocity-examples/leaderboard-robotframework/tests' ]
? [velocity] 1 mirror(s) requested
? [velocity] Mirror process forked with pid 8431
? [velocity] robotframework is starting a mirror at http://localhost:54987/.
? [velocity] You can see the mirror logs at: tail -f /velocity-examples/leaderboard-robotframework/.meteor/local/log/robotframework.log
=> Started your app.   

=> App running at: http://localhost:3000/
? [velocity] Search framework for path tests/robotframework/arguments.txt
? [velocity] Target framework for tests/robotframework/arguments.txt is robotframework
? [velocity] Found fixture file tests/robotframework/fixtures/leaderboard-fixture.js
? [velocity] Search framework for path tests/robotframework/suites/leaderboard-resources.txt
? [velocity] Target framework for tests/robotframework/suites/leaderboard-resources.txt is robotframework
? [velocity] Search framework for path tests/robotframework/suites/leaderboard.txt
? [velocity] Target framework for tests/robotframework/suites/leaderboard.txt is robotframework
? [velocity] Search framework for path tests/robotframework/suites/selenium-resources.txt
? [velocity] Target framework for tests/robotframework/suites/selenium-resources.txt is robotframework
? [velocity] File scan complete, now watching /tests
? [velocity] Triggering queued startup functions
? [velocity] Mirror registered. Handshaking with mirror...
? [velocity] Connected to mirror, setting state to ready { framework: 'robotframework',
?   port: '54987',
?   host: 'http://localhost:54987/' }
? [rsbatech:robotframework] Robot Framework is running
? [rsbatech:robotframework] PhantomJS BinPath: /.meteor/packages/rsbatech_robotframework/.0.4.0.23net3++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/phantomjs/lib/phantom/bin/phantomjs
? [rsbatech:robotframework] ChromeDriver BinPath:/.meteor/packages/rsbatech_robotframework/.0.4.0.23net3++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chromedriver/lib/chromedriver/chromedriver
? [ '--argumentfile',
?   '/velocity-examples/leaderboard-robotframework/tests/robotframework/arguments.txt',
?   '--outputdir',
?   '/velocity-examples/leaderboard-robotframework/tests/robotframework/.logs',
?   '--variable',
?   'MIRROR_URL:http://localhost:54987/',
?   '--variable',
?   'PHANTOMJS_BINPATH:/.meteor/packages/rsbatech_robotframework/.0.4.0.23net3++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/phantomjs/lib/phantom/bin/phantomjs',
?   '--variable',
?   'CHROMEDRIVER_BINPATH:/.meteor/packages/rsbatech_robotframework/.0.4.0.23net3++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chromedriver/lib/chromedriver/chromedriver',
?   '/velocity-examples/leaderboard-robotframework/tests/robotframework/suites' ]
? (STDERR)
? (STDERR) events.js:72
? (STDERR)         throw er; // Unhandled 'error' event
? (STDERR)               ^
? (STDERR) Error: spawn ENOTDIR
? (STDERR)     at errnoException (child_process.js:1011:11)
? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
=> Exited with code: 8

**Comment by rjsmith** [comment]
Hi,
Well, I wonder if it is failing at this line https://github.com/rjsmith/meteor-robotframework/blob/master/server.js#L122

Could it be that 'pybot' is not available on the $PATH on your system ? On mine I get:

```
$ which pybot
/usr/local/bin/pybot
```

~~Another possible clue is that the PATHs printed out in your trace appear to be relative to some root, and not the system root.? Or is that where you are running your meteor project ? For example, on my system, I have this:~~

```
'PHANTOMJS_BINPATH:/Users/richardsmith/.meteor/packages/rsbatech_robotframework/.0.4.0.rbm7gn++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/phantomjs/lib/phantom/bin/phantomjs',
```

EDIT: doh! sorry - just read your info about removing sections of the paths in your trace, so pls ignore my 2nd question! 

btw - v. excited about your meteor-RF talk. I am kind of surprised anyone is using it actually, instead of xolvio:cucumber. Would be really interested to find out more about your use case.

**Comment by mattjmorris** [comment]
Thank you for figuring out it could be my $PATH settings! That made sense since I've had multiple python versions on my machine. After fiddling with $PATH a bit everything ran just fine. 

It's going to be great to have robot tests running via Velocity. I have some experience with cucumber but after seeing your integration of the robot framework I looked into the robot syntax and found it to be more elegant and flexible. So far it's seeming more productive.

Thanks again for the help - I really appreciate it.

**Comment by rjsmith** [comment]
That's good news. Is there any more info you could share in the way of an addition to the README that might help other folk who hit the same / similar issue in the future?  Very happy to accept a PR.

The user guide has a section on configuring $PATH http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#configuring-path

**Comment by mattjmorris** [comment]
The only thing I can think of that might have helped me figure out the problem sooner is if I had read through the linked robotframework guide more carefully and had verified the execution of the runner scripts via $ pybot --version, as documented here:

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#verifying-installation

Not sure what to add to the README other than perhaps a direct link to that section as well.
